# Generated by Django 2.0 on 2020-04-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'valeur'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='titre',
            new_name='valeur',
        ),
        migrations.RemoveField(
            model_name='article',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='article',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
    ]
